[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mixtura"
version = "1.30"
description = "Mixed together. Running everywhere."
authors = [
  { name = "Miguel Batista Pinotti", email = "miguelpinotty@gmail.com" },
  { name = "Leoni Frazão de Oliveira, email = "leoni.frazao.oliveira@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "rich>=13.0.0",
    "shellingham>=1.5.0",
    "typer>=0.9.0",
    "typing-extensions>=4.13.2",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]
build = [
    "nuitka[onefile]>=4.0.0",
    "patchelf>=0.17.0.0",
    "zstandard>=0.22.0",
]

[project.scripts]
mixtura = "mixtura.cli:app"
mix = "mixtura.cli:app"

[tool.setuptools.packages.find]
where = ["."]
include = ["mixtura*"]
namespaces = false

[tool.setuptools.package-data]
mixtura = ["VERSION"]
