# Thanks for the help https://github.com/lucasgab2230
name: Build and Commit Binary

on:
  push:
    branches:
      - "**"
    paths:
      - "src/**"
      - "flake.nix"
      - "Makefile"
      - ".github/workflows/compile.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod

      - name: Test
        working-directory: src
        run: go test ./...

      - name: Compile
        run: ./src/build.sh

      - name: Commit and Push
        run: |
          VERSION=$(cat src/VERSION)
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/mixtura bin/HASH bin/VERSION src
          git commit -m "chore: update compiled binary to v${VERSION} [skip ci]" || echo "No changes to commit"
          git push
