# Thaks for the help https://github.com/lucasgab2230
name: Build and Commit Binary

on:
  push:
    branches:
      - "**"
    paths:
      - "mixtura/**"
      - "build/build.sh"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/compile.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf gcc make
          uv sync --extra build --locked

      - name: Compile
        run: |
          chmod +x build/build.sh
          uv run --extra build ./build/build.sh

      - name: Update lockfile
        run: uv lock

      - name: Commit and Push
        run: |
          VERSION=$(cat bin/VERSION)
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/mixtura bin/HASH bin/VERSION mixtura/VERSION pyproject.toml uv.lock flake.nix
          git commit -m "chore: update compiled binary to v${VERSION} [skip ci]" || echo "No changes to commit"
          git push
